services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dolly_parton
      MYSQL_USER: jb
      MYSQL_PASSWORD: password
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
  server:
    restart: always
    build:
      context: .
      target: final
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - SQL_USERNAME=${SQL_USERNAME}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - HOSTNAME=${HOSTNAME}
      - GUILD_ID=${GUILD_ID}
      - OLLAMA_URL=${OLLAMA_URL}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - OLLAMA_SYSTEM_MESSAGE=${OLLAMA_SYSTEM_MESSAGE}
      - RESPOND_TO_ALL_MESSAGES=${RESPOND_TO_ALL_MESSAGES}
      - RESPONDS_TO=${RESPONDS_TO}
    depends_on:
      - mariadb
    volumes:
      - ai_data:/context
volumes:
  mariadb_data:
  ai_data:
